# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-30 13:58
from __future__ import unicode_literals

import cms.multidb
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpagepermission',
            name='group',
            field=cms.multidb.RoutingForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='globalpagepermission',
            name='user',
            field=cms.multidb.RoutingForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='pagepermission',
            name='group',
            field=cms.multidb.RoutingForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='pagepermission',
            name='user',
            field=cms.multidb.RoutingForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='pageuser',
            name='created_by',
            field=cms.multidb.RoutingForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pageusergroup',
            name='created_by',
            field=cms.multidb.RoutingForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_usergroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=cms.multidb.RoutingOneToOneField(db_constraint=False, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='djangocms_usersettings', to=settings.AUTH_USER_MODEL),
        ),
    ]
