# Generated by Django 3.2.4 on 2024-12-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20170630_1558'),
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
    ]

    operations = [
    ]