# Generated by Django 3.2.4 on 2024-12-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20170630_1558'),
        ('cms', '0039_remove_page_languages_alter_pageurl_unique_together'),
    ]

    operations = [
    ]
